Feat/py secrets manager store
configu/configu pull request #126
Opened 2023-06-19 23:01 UTC by jamesL92

2023-06-20 18:15 UTC, jamesL92 commented
Made a few additional changes:
- unfortunately can't store `boto3.client` as an instance member on `AWSSecretsManagerStore`, since `boto3.client` has a `threading.Lock` member which can't be serialised, i.e. it can't be passed through to a thread as part of `EvalCommand._eval_from_parameters`.
- Small change in where `ConfigStore` is imported from in `key_value_store.py` to make it  consistent with the rest of the stores (was causing a weird issue whereby it wasn't being considered an instance of `ConfigStore` by `pydantic`, meaning it couldn't be used in `EvalCommandParameters`.

2023-06-21 08:25 UTC, RonConfigu commented
Hi JamesL92,

I wanted to commend you on the outstanding work you’ve done thus far. Your contributions are greatly appreciated.

We have recently made some modifications to the SDK (@configu/ts), and I am currently working on updating the py-sdk accordingly. It seems highly likely that the threading functionality will be removed, which means your previous implementation should align perfectly without requiring you to rebuild the client for each call. (see https://github.com/configu/configu/issues/129)

I anticipate that the new version will be published no later than tomorrow, and once that happens, we will proceed to make your pull request operational and ready for merging.

Thank you once again for your efforts.

Best regards,
Ron

2023-06-25 09:36 UTC, RonConfigu requested changes
🚀 💯 Great job! 

The added docstrings are amazing. Thank you for that! much needed.
Please review my comments and apply the suggestions. once done. we're good to go!

Thanks,
Ron

2023-06-25 09:36 UTC, RonConfigu commented on py/configu/stores/aws_secrets_manager_store.py
> +        except Exception:
```suggestion
        except (Exception,):
```
NIT

2023-06-25 16:49 UTC, jamesL92 commented on py/configu/stores/key_value_store.py
> +        If `set` is populated, will use that. Otherwise defaults to `key`
:+1: makes perfect sense, thanks for the explanation :)

2023-06-25 17:00 UTC, jamesL92 commented
@RonConfigu I've made the requested changes, please let me know if any further changes are required :+1:

2023-06-26 06:34 UTC, RonConfigu approved these changes
Beautiful work. 🥇 
Thank you for your contribution @jamesL92!

We would be delighted to mention your contribution and show you our appreciation on our LinkedIn. If you are interested, please provide us with your LinkedIn account details or email.

2023-06-26 06:35 UTC, merged