Using `string constants` for `error messages`
configu/configu pull request #210
Opened 2023-08-15 21:17 UTC by Sadaf-A

This PR adds string constants for errors.
Resolves #208

2023-08-15 21:52 UTC, Sadaf-A commented
I believe same can be done for suggestion messages

2023-08-16 13:59 UTC, RonConfigu reviewed
Hi @Sadaf-A,

Thank you for opening the issue and this PR. 💯

This issue has been lingering in the back of our minds for a while now, and seeing the community address it definitely elevates its importance.

That being said, we will need to devise a comprehensive solution for this and establish its infrastructure before these changes can be applied.

We will get in touch with you once such a plan is in place, and we would be delighted to accept your contribution.

Thanks, Ron

2023-08-16 22:21 UTC, jamesL92 requested changes

2023-08-16 22:21 UTC, jamesL92 commented on ts/packages/ts/src/ErrorConstants.ts
> +
A few more trailing newlines than needed :sweat_smile:

2023-08-27 14:16 UTC, rannn505 commented
@Sadaf-A, thank you for your input. As @RonConfigu pointed out, we're planning a comprehensive consolidation of our error messages across the entire project. I'll keep you updated on when we kickstart this initiative, and we'd welcome your contribution on the respective PR.

2023-08-27 14:16 UTC, closed without merging