Implement `MongoDB` `ConfigStore` in Node.js SDK
configu/configu pull request #252
Opened 2023-09-12 18:04 UTC by Sadaf-A

Resolves #146'

2023-09-24 10:42 UTC, rannn505 commented
@Sadaf-A is it WIP?

2023-09-24 10:48 UTC, Sadaf-A commented
> @Sadaf-A is it WIP?

Yes, for now I've only tried to connect to mongo
what else is required upsert and eval?
Please let me know how this file is supposed to behave
Thank you

2023-09-30 18:00 UTC, rannn505 commented
@Sadaf-A it should implement the `get` and the `set` methods of the Base ConfigStore class with the `mongo` driver or with the TypeORM base class

2023-10-11 14:15 UTC, RichardAkman commented on ts/packages/node/src/index.ts
> +export * from './stores/MongoDb';
Please keep the naming consistent with other stores:
```suggestion
export * from './stores/MongoDB';
```

2023-10-11 14:16 UTC, RichardAkman commented on ts/packages/node/src/stores/MongoDb.ts
Please keep the naming of the file consistent with the other stores like `MariaDB` -> `MongoDB`

2023-10-11 14:19 UTC, RichardAkman commented on ts/packages/node/src/stores/MongoDb.ts
Please refactor the current implementation to extend `ORMConfigStore` instead of directly re-implementing the same existing logic within the `typeorm` abstract class 🙏🏻

2023-10-11 14:21 UTC, RichardAkman requested changes
Thanks a lot for your contribution 🏅 , please apply my comments let's see this PR through!

2023-10-30 08:20 UTC, RichardAkman requested changes
@Sadaf-A, I tried checking out your PR to test your changes but the store does not work. 

![image](https://github.com/configu/configu/assets/47181182/477dcf47-f826-44ec-9923-0be5b9600a57)

When you use the ORM package, it expects you to have the necessary dependencies installed. Please add the necessary dependency and run some tests to make sure everything works as expected.

As a side note, I'm not entirely sure why you decided to override the logic that already exists in ORM, If you can explain the reasoning it would make the CR go smoother.

2023-11-01 12:54 UTC, rannn505 commented
Hi @Sadaf-A,

First off, we want to sincerely thank you for the time and effort you've invested in this Pull Request. Your willingness to contribute is greatly appreciated by our team.

However, we've noticed that there hasn't been any progress on this PR for quite some time. In the interest of maintaining a streamlined and efficient development process, we're going to close this PR for the time being.

That being said, we're more than willing to help you identify what's needed to complete this PR. If you would like support in figuring out the missing pieces or have any questions, please don't hesitate to reach out. Once you have a working code and are ready to proceed, we encourage you to reopen the PR.

Thanks again for your understanding and your contributions to our project. We're looking forward to seeing your work come to fruition.

2023-11-01 12:54 UTC, closed without merging