Add toml config store
configu/configu pull request #312
Opened 2023-11-15 10:23 UTC by zmar636

TOML Config store 
#268

2023-11-16 20:01 UTC, zmar636 commented
Hi @RonConfigu can you provide feedback on this PR ? 

Thank you

2023-11-19 09:27 UTC, RichardAkman commented on ts/packages/node/src/stores/TomlFile.ts
> +export class TomlFileConfigStore extends ConfigStore {
Please change `TomlFileConfigStore` to extend `FileConfigStore`. You can take reference from the INI config store regarding the implementation due to the similarities between INI and TOML files.

2023-11-19 09:29 UTC, RichardAkman commented on ts/packages/node/src/stores/TomlFile.ts
> +import { ConfigStore, ConfigStoreQuery, Config, Convert } from '@configu/ts';
Please make sure to run `npm run lint` to make sure the code is linted according to the linting rules of the project.

2023-11-19 09:31 UTC, RichardAkman commented on ts/packages/node/src/stores/TomlFile.ts
> +import toml from '@iarna/toml';
This requires the addition of the package in the dependencies in `package.json`.

2023-11-19 09:31 UTC, RichardAkman commented on ts/packages/node/src/stores/TomlFile.test.ts
> +import { Config } from '@configu/ts';
Please make sure to run npm run lint to make sure the code is linted according to the linting rules of the project.

2023-11-19 09:33 UTC, RichardAkman requested changes
Great work! Please review the comments I left you 🙏🏻

2023-11-29 08:27 UTC, RichardAkman commented
Hi @zmar636,

Firstly, I want to express appreciation for your work on this pull request. Your commits have been noticed, and we're grateful for your contributions!

I did notice that there haven't been any requests for a re-review recently, and we're eager to move forward with this feature. If you're currently busy or facing any challenges, that's completely understandable. However, to keep the momentum going and ensure timely progress, it would be great to know if you plan to continue working on this PR soon.

In the absence of a re-review request, we're considering closing this PR to give others the opportunity to contribute. If you're still interested in completing this PR or have any questions, please let us know.

Thanks for your understanding and cooperation.

2023-12-11 09:31 UTC, RichardAkman commented
Hi @zmar636,

Due to inactivity, we have decided to close this PR to allow other contributors to work on this issue.

Thanks for your understanding and cooperation.

2023-12-11 09:31 UTC, closed without merging