Implement CSV ConfigStore in Node.js SDK
configu/configu pull request #394
Opened 2024-03-11 21:32 UTC by Maran1947

Closes #151 
Hi @RichardAkman, Can you please take a moment to review it?

2024-03-12 11:46 UTC, RichardAkman commented on ts/packages/node/src/stores/CsvFile.ts
> +  }
We should utilize the capabilities of the `csv` package to streamline these methods:

```suggestion
  parse(fileContent: string): Config[] {
    return parse(fileContent, { columns: true });
  }

  stringify(nextConfigs: Config[]): string {
    return stringify(nextConfigs, { header: true });
  }
```

2024-03-12 11:48 UTC, RichardAkman requested changes
Great work, your experience implementing config stores is really showing ⭐ 

Take a look at my suggestion and then we can finalize this PR 🚀

2024-03-12 15:07 UTC, Maran1947 commented
Thanks for appreciation. I've really enjoyed working on config stores, and your support means a lot to me! 🙌 🙏

I've noticed that the `parse` method breaks when encountering empty lines, so I've added a `skip_empty_lines` attribute to handle this issue. Additionally, I've included a `trim` attribute to handle spaces and tabs. 

Could you please review these changes and suggest any improvements?

2024-03-13 05:48 UTC, RichardAkman approved these changes
I've removed the addition of `trim` as we do not want to mutate the data that the users of the config store are storing. Looks great now, the addition of `skip_empty_lines` is solid. 🏅

2024-03-13 05:51 UTC, merged