Migrate XmlFileConfigStore to @configu/integrations (issue 524)
configu/configu pull request #530
Opened 2024-10-09 17:52 UTC by alfasin

Closes #

2024-10-10 07:14 UTC, davidmeirlevy requested changes
Thanks for your PR!

I wrote some comments. please fix so we can merge. 🙏

2024-10-10 07:14 UTC, davidmeirlevy commented on packages/cli/package.json
> +    "@configu-integrations/xml-file": "workspace:*",
we don't install our integration inside the CLI.

2024-10-10 07:14 UTC, davidmeirlevy commented on packages/cli/src/commands/base.ts
> +    Registry.register({ NoopConfigStore, InMemoryConfigStore, XmlFileConfigStore });
the xml might not be one of the built-in integrations.
please remove from the CLI.

2024-10-10 07:14 UTC, davidmeirlevy commented on packages/integrations/stores/xml-file/src/configs-db.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
is that file used for testing?
if so, it's better to create a test file, and put it inside a "stub" directory. (you can see a testing structure example in (package/common)

2024-10-13 06:54 UTC, davidmeirlevy commented
@alfasin thanks for the PR!
just a few minor fixed, and we can merge. 👏

2024-10-20 08:53 UTC, davidmeirlevy requested changes

2024-10-20 08:53 UTC, davidmeirlevy commented on packages/cli/src/commands/base.ts
> +import { XmlFileConfigStore } from '@configu-integrations/xml-file/src/xml-file';
@alfasin please revert this change as well.

2024-10-21 14:27 UTC, Jonathan-den approved these changes

2024-10-27 09:34 UTC, davidmeirlevy approved these changes

2024-10-27 10:18 UTC, merged

2024-10-27 10:19 UTC, davidmeirlevy commented
@alfasin thanks!!