Migrate TomlFileConfigStore to @configu/integrations
configu/configu pull request #531
Opened 2024-10-09 17:57 UTC by akshay11298

Closes # https://github.com/configu/configu/issues/523

2024-10-10 07:17 UTC, davidmeirlevy requested changes
Thanks for your PR!

please fix the tiny comment I found, so we can merge. 🙏

2024-10-10 09:20 UTC, akshay11298 commented on packages/integrations/stores/toml-file/package.json
> +  },
Thanks... I have updated it

2024-10-13 06:48 UTC, davidmeirlevy approved these changes

2024-10-13 06:49 UTC, merged

2024-10-13 06:50 UTC, davidmeirlevy commented
@akshay11298 merged! thanks!

2024-10-13 06:50 UTC, davidmeirlevy commented
@RichardAkman as we discussed, i ignored the lockfile issue for this PR.
we'll fix all lock problems at the end of the day.