feat: add  etcd to @configu/integrations
configu/configu pull request #551
Opened 2024-10-13 07:14 UTC by su-shubham

Closes #514

2024-10-13 07:40 UTC, davidmeirlevy requested changes
@su-shubham thanks for your PR!

just a minor fix, and we can merge it! 👏

2024-10-13 07:40 UTC, davidmeirlevy commented on packages/integrations/stores/etcd/package.json
> +    "etcd3": "1.1.2",
should be a dependency, not dev.

2024-10-13 08:33 UTC, davidmeirlevy approved these changes
LGTM

2024-10-13 08:51 UTC, merged

2024-10-13 08:52 UTC, davidmeirlevy commented
@su-shubham thanks for your contribution 🚀

2024-11-25 17:12 UTC, pelegpor commented
Hi @su-shubham ,

Here are the details for claiming your Hacktoberfest prizes! 🎉 Check out [#465  (comment)](https://github.com/configu/configu/issues/465#issuecomment-2498550259) for more information or simply fill out the form here: [Claim Your Swag](https://share-eu1.hsforms.com/2SVc5VKY3Thi04Bvjh17WKw2e62o0).  

Remember, you only need to fill out the form once for all your PRs. 😊