Extended Datetime Cfgu Types
configu/configu pull request #567
Opened 2024-10-14 20:54 UTC by JayGaba

1. Duration:

- Added a regex pattern: ^\d+[smhdwMy]$
   -  Description: Validates durations like 1h, 2d, 3w.

2. DateFormat:
- Added a regex pattern: ^(yyyy|yy|MM|M|dd|d|HH|H|mm|m|ss|s)([.-/\s]?(yyyy|yy|MM|M|dd|d|HH|H|mm|m|ss|s))*$
    - Description: Ensures date formats like yyyy-MM-dd or dd/MM/yyyy HH:mm:ss are valid

2024-10-15 09:07 UTC, RichardAkman commented on packages/schema/.cfgu.json
Please update your PR to account for the conflicts with your other PR that we merged 🙏🏻 

Also please remove the type validation from this file, validation of types is the job of `EvalCommand`

2024-10-15 09:07 UTC, RichardAkman requested changes
Please update your PR to account for the conflicts with your other PR that we merged 🙏🏻

Also please remove the type validation from this file, validation of types is the job of EvalCommand

2024-10-15 10:06 UTC, RichardAkman approved these changes
LGTM, thank you for your contributions ⭐ ⭐

2024-10-15 10:06 UTC, merged

2024-11-25 17:10 UTC, pelegpor commented
Hi @JayGaba ,

Here are the details for claiming your Hacktoberfest prizes! 🎉 Check out [#465  (comment)](https://github.com/configu/configu/issues/465#issuecomment-2498550259) for more information or simply fill out the form here: [Claim Your Swag](https://share-eu1.hsforms.com/2SVc5VKY3Thi04Bvjh17WKw2e62o0).  

Remember, you only need to fill out the form once for all your PRs. 😊