feat: Migrate PostgreSQLConfigStore to @configu/integrations
configu/configu pull request #605
Opened 2024-10-21 16:49 UTC by TomerPacific

Closes #508 

This pull request introduces a new PostgreSQL configuration store integration to the project. The main changes include the addition of a new package, its configuration, and dependencies.

### New PostgreSQL Configuration Store Integration:

* **Package Addition:**
  - Added `package.json` for the new PostgreSQL configuration store package. (`packages/integrations/stores/postgre-sql-config-store/package.json`)

* **Source Code Implementation:**
  - Implemented the `PostgreSQLConfigStore` class, extending `ORMConfigStore` with PostgreSQL-specific configurations. (`packages/integrations/stores/postgre-sql-config-store/src/postgre-sql-config-store.ts`)

* **Configuration Files:**
  - Added `tsconfig.json` to extend the base TypeScript configuration. (`packages/integrations/stores/postgre-sql-config-store/tsconfig.json`)
  - Added `tsup.config.ts` for the build configuration using `tsup`. (`packages/integrations/stores/postgre-sql-config-store/tsup.config.ts`)

* **Dependency Management:**
  - Updated `pnpm-lock.yaml` to include dependencies and devDependencies for the new package. (`pnpm-lock.yaml`)

2024-10-22 07:20 UTC, RichardAkman commented on packages/integrations/stores/postgre-sql-config-store/package.json
Please refactor the package folder name to `postgresql` instead of `postre-sql-config-store`, there's no need for the `config-store` suffix, other instances of this are mistakes, and also `postgresql` is one word. Also, please adjust the all files and mentions of `postgre-sql-config-store` in the files to `postgresql`.

2024-10-22 07:22 UTC, RichardAkman commented on packages/integrations/stores/postgre-sql-config-store/package.json
Please also include a `README.md` file that describes the store and how to use it for users of this integration. Here is a reference PR introducing store documentation from which you can draw inspiration: #575.

2024-10-22 07:23 UTC, RichardAkman requested changes
Great work and thank you for your contribution 🏅

Please review my comments and apply them before we can proceed.

2024-10-22 16:27 UTC, TomerPacific commented on packages/integrations/stores/postgre-sql-config-store/package.json
@RichardAkman - Done.

2024-10-22 16:28 UTC, TomerPacific commented on packages/integrations/stores/postgre-sql-config-store/package.json
@RichardAkman - As I am not familiar with the product or the config store, I might not present the data necessary in the README. I'll give it a go, but I'll probably need some pointers.

2024-10-23 07:08 UTC, RichardAkman commented on packages/integrations/stores/postgre-sql-config-store/package.json
- You should copy the same file structure from the reference PR.
- The examples section is a bonus, you can omit it if you can't reproduce the images.
- The snippets are mostly generic, you only have to modify the `configuration` property in the `.configu` snippet to match the store.
- You can leave the configuration and limitations section to me, I'll go ahead and complete them for you so we can push this PR forward.

2024-10-27 09:08 UTC, RichardAkman approved these changes
Great work 🎖️ 

I've made some minor adjustments to ensure this PR is ready to be merged. Thank you for your contribution!

2024-10-27 09:09 UTC, merged