Migrated `IniFileConfigStore` to `@configu/integrations`
configu/configu pull request #625
Opened 2024-10-27 16:22 UTC by SanchitMahajan236

Closes #516

2024-10-28 08:10 UTC, RichardAkman commented on packages/integrations/stores/ini-file/src/ini.ts
> +import { type Config } from '@configu/ts';
Please replace the use of `@configu/ts` with `@configu/sdk`, make sure to remove the dependency from the `package.json` file.

2024-10-28 08:10 UTC, RichardAkman commented on packages/integrations/stores/ini-file/src/ini.ts
> +import _ from 'lodash';
Replace with `lodash-es` and make sure it's a dependency in `package.json`.

2024-10-28 08:12 UTC, RichardAkman commented on packages/integrations/stores/ini-file/package.json
> +  "name": "@configu-integrations/ini",
```suggestion
  "name": "@configu-integrations/ini-file",
```

2024-10-28 08:14 UTC, RichardAkman commented on packages/integrations/stores/ini-file/package.json
Please also include a `README.md` file and use the same file structure from any of the PRs related to #600.

2024-10-28 08:15 UTC, RichardAkman requested changes
Great work ⭐ , please apply my comments before we can proceed

2024-10-30 08:38 UTC, RichardAkman commented
@SanchitMahajan236 please let us know if you're still working on this PR, if not let us know and we will make the issue available to other contributors 🙏🏻

2024-10-30 09:45 UTC, SanchitMahajan236 commented
Hi @RichardAkman , I have done the changes to the code as mentioned by you and working on the readme file.

2024-10-30 14:42 UTC, SanchitMahajan236 commented
Hi @RichardAkman , I have merged the updates requested.

2024-10-30 14:49 UTC, RichardAkman approved these changes
Amazing work! ⭐ 🚀 

Made a few minor adjustments to align this store with other stores

2024-10-30 14:49 UTC, merged

2024-11-25 17:04 UTC, pelegpor commented
Hi @SanchitMahajan236 ,

Here are the details for claiming your Hacktoberfest prizes! 🎉 Check out [#465  (comment)](https://github.com/configu/configu/issues/465#issuecomment-2498550259) for more information or simply fill out the form here: [Claim Your Swag](https://share-eu1.hsforms.com/2SVc5VKY3Thi04Bvjh17WKw2e62o0).  

Remember, you only need to fill out the form once for all your PRs. 😊